image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r index.html app.css app.js manifest.webmanifest sw.js data icons public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
